### ISSUE TITLE
Fix Filepaths for Memes and Templates

### ISSUE THREAD

**Issue by jonchan51** [AY1920S1-CS2103-T16-3/main#127]
Right now, file paths all include the folders they are in, i.e. data/memes or data/templates for the default case. However, this means that if we change the folder specified in preferences.json, and copy the respective image folders to the new locations, Weme will still not work due to images having incorrect paths. 

Hence there is a need to change the file paths to only contain the filename.extension, and read all the memes and templates via the folder specified in the preferences.json

Edit: Don't know whether my suggestion works, need to think through everything clearly. The main problem to address is that when the user changes the file path specified in the preferences, everything breaks

**Comment by moziliar** [comment]
The internal path within Weme should be consistent and invisible to the user. If we store the filePath as relative path within Weme, moving Weme around would not corrupt the reading of the files. Are we going to store the images within the jar file or in a separate folder outside the jar?

**Comment by moziliar** [comment]
Btw storing the filename only means we don't even need path... Just a String will do.

**Comment by jonchan51** [comment]
We need to change the preferences.json then, right now users are able to modify the path of the individual image directories, should discuss how to approach this entire matter of moving data files around

**Comment by moziliar** [comment]
@LivingOnEdge should we disable it? And also, @jonchan51 is the image directory inside the Jar file? If so I suggest just disallow the user to change it.

**Comment by LivingOnEdge** [comment]
We should not allow for modification of the path inside the application. Only export path.
