### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by jonchan51** [AY1920S1-CS2103-T16-3/main#138]
Our user guide mentioned add, delete, edit for tags, are we planning to keep them or remove them? Right now the only way to add tags is by listing all the tags currently on a meme then adding the tag at the end, which clearly isn't ideal.

**Comment by moziliar** [comment]
I don’t think we need to add a tag independent of any meme. Just edit a meme and add a new tag to it. We don’t quite have a place to store the tags (my TagManager could be one but do we really have to add a tag out of no where?).

**Comment by jonchan51** [comment]
In this case the add tag was a command to append a tag to a meme's already existing tag list, not to create a new tag that has no meme attached to it.
