### ISSUE TITLE
New meme fails to display after creation

### ISSUE THREAD

**Issue by cutieprobe** [AY1920S1-CS2103-T16-3/main#214]
Problem: new meme fails to display in meme tab immediately after creation. After restarting the application, new meme displays fine.

Before `create` command;
![1](https://user-images.githubusercontent.com/45759668/68299439-a89bb700-00d6-11ea-89d6-e3c2c2e2ea9b.png)
After `create` command:
![2](https://user-images.githubusercontent.com/45759668/68299459-af2a2e80-00d6-11ea-9c74-d4cd7bf13b4f.png)

**Comment by jonchan51** [comment]
Caused by dislike not being updated when you add a meme
