### ISSUE TITLE
Tag length issue

### ISSUE THREAD

**Issue by moziliar** [AY1920S1-CS2103-T16-3/main#243]
Limit length of tag for display, or limit the length of tag in general (since user won't need such a long tag.)
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/19870898/68494512-85653900-0289-11ea-8171-8181f7dd0453.png">

**Comment by moziliar** [comment]
Option 1: limit length of tag name in isValidTagName()
Option 2: limit the display length of tag name (truncate overflow characters and put "..")

**Comment by jonchan51** [comment]
Would prefer option 1, try to limit it to within the size of one grid cell.

**Comment by moziliar** [comment]
Since we are on it, shall we also truncate whatever that overflow? Currently if there are multiple lines of tags, the content (description, likes) will be pushed down. Can we hide some tags that might push down the content and truncate the description?

**Comment by jonchan51** [comment]
yes pls, that's the main reason for view
