### ISSUE TITLE
Sample memes not included in jar file

### ISSUE THREAD

**Issue by gary-lgy** [AY1920S1-CS2103-T16-3/main#45]
Sample memes are not included in the resultant jar file.
New users without `src/main/resources/memes` are unable to run the jar file.

**Comment by moziliar** [comment]
Is it possible to do like Duke?

**Comment by gary-lgy** [comment]
> Is it possible to do like Duke?

Yes. We'll have to modify `SampleDataUtil` to get file path dynamically instead of using hard coded paths. Probably need to copy the files somehow before loading the memes.
